<div>
<section class="content-header"><div class="container-fluid"><button type="button" class="btn btn-outline-primary float-sm-right mb-2" data-toggle="modal" data-target="#billingProfileModal">Billing profile</button><h1>Subscription &amp; Billing</h1><p class="text-muted">Plan, allowance, invoices, payments and change requests for {{ $clinic->name }}.</p></div></section><section class="content"><div class="container-fluid">
@if(session('subscription_message'))<div class="alert alert-success">{{ session('subscription_message') }}</div>@endif
@if(!$subscription)<div class="alert alert-danger">No subscription is assigned to {{ $clinic->name }}. Contact the platform administrator.</div>@else
@php($plan=$subscription->plan_snapshot??[]) @php($pricing=$subscription->pricing_snapshot??[])
<div class="row"><div class="col-lg-4"><div class="card card-primary card-outline h-100"><div class="card-body"><small class="text-uppercase text-muted">Current plan</small><h2>{{ $plan['name']??$subscription->plan?->name }}</h2><p class="mb-1"><span class="badge badge-info">{{ \App\Support\PlanProduct::label(\App\Support\PlanProduct::productOf($subscription->feature_snapshot)) }}</span></p><span class="badge badge-{{ in_array($subscription->status,['active','trial'])?'success':($subscription->status==='overdue'?'warning':'danger') }}">{{ strtoupper($subscription->status) }}</span><hr><p><b>Billing:</b> {{ ucfirst($subscription->billing_interval) }}</p><p><b>Price:</b> {{ $pricing['currency']??'GHS' }} {{ number_format((float)($subscription->billing_interval==='yearly'?($pricing['annual_price']??0):($pricing['base_price']??0)),2) }}</p><p><b>Renewal:</b> {{ $subscription->current_period_ends_at?->format('d M Y')??'Not scheduled' }}</p></div></div></div>
<div class="col-lg-8"><div class="card h-100"><div class="card-header"><h3 class="card-title">Current usage</h3></div><div class="card-body"><div class="row">
@foreach([['Branches',$usage['branches'],$subscription->branchLimit()],['Users',$usage['users'],$plan['included_users']??null],['Storage (MB)',$usage['storage_mb'],$plan['storage_limit_mb']??null]] as [$label,$used,$limit])<div class="col-md-6 mb-3"><div class="d-flex justify-content-between"><b>{{ $label }}</b><span>{{ $used }} / {{ $limit??'Unlimited' }}</span></div>@if($limit)<div class="progress mt-2"><div class="progress-bar {{ $used>$limit?'bg-danger':'' }}" style="width:{{ min(100,round($used/$limit*100)) }}%"></div></div>@endif</div>@endforeach<div class="col-md-6 mb-3"><div class="d-flex justify-content-between"><b>SMS credits</b><span>{{ number_format($smsCredits) }} left</span></div><small class="text-muted">Bought separately from your plan in <a href="{{ route('admin.settings', ['tab' => 'sms']) }}">Settings → SMS</a>. Credits never expire.</small></div>
</div></div></div></div></div>
@endif
<div class="card mt-3"><div class="card-header"><h3 class="card-title">Invoices and payments</h3></div><div class="card-body table-responsive p-0"><table class="table table-hover"><thead><tr><th>Invoice</th><th>Period</th><th>Due</th><th>Total</th><th>Paid</th><th>Status</th><th>Documents</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td>{{ $invoice->number }}</td><td>{{ $invoice->period_start->format('d M Y') }} – {{ $invoice->period_end->format('d M Y') }}</td><td>{{ $invoice->due_date->format('d M Y') }}</td><td>{{ $invoice->currency }} {{ number_format((float)$invoice->total,2) }}</td><td>{{ number_format((float)$invoice->amount_paid,2) }}</td><td><span class="badge badge-{{ $invoice->status==='paid'?'success':($invoice->status==='partial'?'warning':'danger') }}">{{ strtoupper($invoice->status) }}</span></td><td><a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ route('admin.subscription.invoice',$invoice) }}">Invoice</a>@if($invoice->status==='paid') <a class="btn btn-sm btn-outline-success" target="_blank" href="{{ route('admin.subscription.receipt',$invoice) }}">Receipt</a>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">No invoices have been issued.</td></tr>@endforelse</tbody></table></div></div>
<div class="row"><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Request plan change</h3></div><form wire:submit="requestPlanChange"><div class="card-body"><select class="form-control mb-3" wire:model="requestedPlanId"><option value="">Select plan</option>@foreach($plans->groupBy(fn($p)=>$p->product?:'both') as $product=>$group)<optgroup label="{{ \App\Support\PlanProduct::label($product) }}">@foreach($group as $available)<option value="{{ $available->id }}">{{ $available->name }} — {{ $available->currency }} {{ $available->base_price }}/month</option>@endforeach</optgroup>@endforeach</select><select class="form-control mb-3" wire:model="requestedInterval"><option value="monthly">Monthly billing</option><option value="yearly">Annual billing</option></select><textarea class="form-control" wire:model="requestMessage" placeholder="Optional message"></textarea>@error('requestedPlanId')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="card-footer"><button class="btn btn-primary">Submit request</button></div></form></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Request history</h3></div><div class="card-body">@forelse($requests as $request)<div class="border-bottom pb-2 mb-2"><b>{{ $request->requestedPlan->name }}</b> · {{ ucfirst($request->billing_interval) }} <span class="badge badge-secondary float-right">{{ strtoupper($request->status) }}</span><small class="d-block text-muted">{{ $request->created_at->format('d M Y H:i') }}</small></div>@empty<p class="text-muted">No plan-change requests.</p>@endforelse</div></div></div></div>
<div class="card mt-3"><div class="card-header"><h3 class="card-title">Contract history</h3></div><div class="card-body table-responsive p-0"><table class="table"><thead><tr><th>Plan</th><th>Version</th><th>Terms</th><th>Recorded</th><th>Source</th></tr></thead><tbody>@forelse($agreements as $agreement)<tr><td>{{ data_get($agreement->plan_snapshot,'name','Unknown') }}</td><td>{{ $agreement->plan_family_code }} v{{ $agreement->plan_version }}</td><td>v{{ $agreement->terms_version }}</td><td>{{ $agreement->accepted_at?->format('d M Y H:i') }}</td><td>{{ ucwords(str_replace('_',' ',$agreement->source)) }}</td></tr>@empty<tr><td colspan="5" class="text-muted">No contract history recorded.</td></tr>@endforelse</tbody></table></div></div>
</div></section>
<div wire:ignore.self class="modal fade" id="billingProfileModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form wire:submit="saveBillingProfile"><div class="modal-header"><h5>Billing profile</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input class="form-control mb-2" wire:model="billingLegalName" placeholder="Legal billing name"><input class="form-control mb-2" wire:model="billingTaxId" placeholder="Tax ID / TIN"><textarea class="form-control mb-2" wire:model="billingAddress" placeholder="Billing address"></textarea><input class="form-control mb-2" wire:model="billingEmail" type="email" placeholder="Billing email"><input class="form-control" wire:model="billingPhone" placeholder="Billing phone"></div><div class="modal-footer"><button class="btn btn-primary">Save billing profile</button></div></form></div></div></div>
</div>
