<div class="clinic-ui ui-page">
<section class="content-header"><div class="w-full"><button type="button" class="btn ui-button ui-button-secondary float-sm-right mb-2" data-toggle="modal" data-target="#billingProfileModal">Billing profile</button><h1>Subscription &amp; Billing</h1><p class="text-slate-500">Plan, allowance, invoices, payments and change requests for {{ $clinic->name }}.</p></div></section><section class="content"><div class="w-full">
<x-ui.flash :map="['subscription_message' => 'success']" />
@if(!$subscription)<div class="rounded-lg border px-3 py-2 text-sm border-red-200 bg-red-50 text-red-800">No subscription is assigned to {{ $clinic->name }}. Contact the platform administrator.</div>@else
@php($plan=$subscription->plan_snapshot??[]) @php($pricing=$subscription->pricing_snapshot??[])
<div class="flex flex-wrap -mx-2"><div class="w-full lg:w-4/12 px-2"><div class="card overflow-hidden rounded-xl border border-slate-200 bg-white card-primary h-full"><div class="card-body p-4"><small class="uppercase text-slate-500">Current plan</small><h2>{{ $plan['name']??$subscription->plan?->name }}</h2><p class="mb-1"><span class="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-semibold bg-sky-100 text-sky-800">{{ \App\Support\PlanProduct::label(\App\Support\PlanProduct::productOf($subscription->feature_snapshot)) }}</span></p><span class="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-semibold badge-{{ in_array($subscription->status,['active','trial'])?'success':($subscription->status==='overdue'?'warning':'danger') }}">{{ strtoupper($subscription->status) }}</span><hr><p><b>Billing:</b> {{ ucfirst($subscription->billing_interval) }}</p><p><b>Price:</b> {{ $pricing['currency']??'GHS' }} {{ number_format((float)($subscription->billing_interval==='yearly'?($pricing['annual_price']??0):($pricing['base_price']??0)),2) }}</p><p><b>Renewal:</b> {{ $subscription->current_period_ends_at?->format('d M Y')??'Not scheduled' }}</p></div></div></div>
<div class="w-full lg:w-8/12 px-2"><div class="card overflow-hidden rounded-xl border border-slate-200 bg-white h-full"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><h3 class="font-semibold">Current usage</h3></div><div class="card-body p-4"><div class="flex flex-wrap -mx-2">
@foreach([['Branches',$usage['branches'],$subscription->branchLimit()],['Users',$usage['users'],$plan['included_users']??null],['Storage (MB)',$usage['storage_mb'],$plan['storage_limit_mb']??null]] as [$label,$used,$limit])<div class="w-full md:w-6/12 px-2 mb-4"><div class="flex justify-between"><b>{{ $label }}</b><span>{{ $used }} / {{ $limit??'Unlimited' }}</span></div>@if($limit)<div class="h-2 overflow-hidden rounded-full bg-slate-200 mt-2"><div class="h-full bg-teal-600 {{ $used>$limit?'bg-red-600 text-white':'' }}" style="width:{{ min(100,round($used/$limit*100)) }}%"></div></div>@endif</div>@endforeach<div class="w-full md:w-6/12 px-2 mb-4"><div class="flex justify-between"><b>SMS credits</b><span>{{ number_format($smsCredits) }} left</span></div><small class="text-slate-500">Bought separately from your plan in <a href="{{ route('admin.sms-settings') }}">Communications → SMS Credits & Sending</a>. Credits never expire.</small></div>
</div></div></div></div></div>
@endif
<div class="card overflow-hidden rounded-xl border border-slate-200 bg-white mt-4"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><h3 class="font-semibold">Invoices and payments</h3></div><div class="card-body ui-table-wrap p-0"><table class="table ui-table"><thead><tr><th>Invoice</th><th>Period</th><th>Due</th><th>Total</th><th>Paid</th><th>Status</th><th>Documents</th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td>{{ $invoice->number }}</td><td>{{ $invoice->period_start->format('d M Y') }} – {{ $invoice->period_end->format('d M Y') }}</td><td>{{ $invoice->due_date->format('d M Y') }}</td><td>{{ $invoice->currency }} {{ number_format((float)$invoice->total,2) }}</td><td>{{ number_format((float)$invoice->amount_paid,2) }}</td><td><span class="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-semibold badge-{{ $invoice->status==='paid'?'success':($invoice->status==='partial'?'warning':'danger') }}">{{ strtoupper($invoice->status) }}</span></td><td><a class="btn ui-button ui-button-sm ui-button-secondary" target="_blank" href="{{ route('admin.subscription.invoice',$invoice) }}">Invoice</a>@if($invoice->status==='paid') <a class="btn ui-button ui-button-sm ui-button-secondary" target="_blank" href="{{ route('admin.subscription.receipt',$invoice) }}">Receipt</a>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-slate-500 py-6">No invoices have been issued.</td></tr>@endforelse</tbody></table></div></div>
<div class="flex flex-wrap -mx-2"><div class="w-full lg:w-6/12 px-2"><div class="card overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><h3 class="font-semibold">Request plan change</h3></div><form wire:submit="requestPlanChange"><div class="card-body p-4"><select class="form-control ui-input mb-4" wire:model="requestedPlanId"><option value="">Select plan</option>@foreach($plans->groupBy(fn($p)=>$p->product?:'both') as $product=>$group)<optgroup label="{{ \App\Support\PlanProduct::label($product) }}">@foreach($group as $available)<option value="{{ $available->id }}">{{ $available->name }} — {{ $available->currency }} {{ $available->base_price }}/month</option>@endforeach</optgroup>@endforeach</select><select class="form-control ui-input mb-4" wire:model="requestedInterval"><option value="monthly">Monthly billing</option><option value="yearly">Annual billing</option></select><textarea class="form-control ui-input" wire:model="requestMessage" placeholder="Optional message"></textarea>@error('requestedPlanId')<small class="text-red-700">{{ $message }}</small>@enderror</div><div class="border-t border-slate-200 bg-slate-50 px-4 py-2"><button class="btn ui-button ui-button-primary">Submit request</button></div></form></div></div>
<div class="w-full lg:w-6/12 px-2"><div class="card overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><h3 class="font-semibold">Request history</h3></div><div class="card-body p-4">@forelse($requests as $request)<div class="border-b border-slate-200 pb-2 mb-2"><b>{{ $request->requestedPlan->name }}</b> · {{ ucfirst($request->billing_interval) }} <span class="inline-flex items-center rounded px-1.5 py-0.5 text-xs font-semibold bg-slate-100 text-slate-700 float-right">{{ strtoupper($request->status) }}</span><small class="block text-slate-500">{{ $request->created_at->format('d M Y H:i') }}</small></div>@empty<p class="text-slate-500">No plan-change requests.</p>@endforelse</div></div></div></div>
<livewire:admin.clinic-addons-component />
<div class="card overflow-hidden rounded-xl border border-slate-200 bg-white mt-4"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><h3 class="font-semibold">Contract history</h3></div><div class="card-body ui-table-wrap p-0"><table class="table ui-table"><thead><tr><th>Plan</th><th>Version</th><th>Terms</th><th>Recorded</th><th>Source</th></tr></thead><tbody>@forelse($agreements as $agreement)<tr><td>{{ data_get($agreement->plan_snapshot,'name','Unknown') }}</td><td>{{ $agreement->plan_family_code }} v{{ $agreement->plan_version }}</td><td>v{{ $agreement->terms_version }}</td><td>{{ $agreement->accepted_at?->format('d M Y H:i') }}</td><td>{{ ucwords(str_replace('_',' ',$agreement->source)) }}</td></tr>@empty<tr><td colspan="5" class="text-slate-500">No contract history recorded.</td></tr>@endforelse</tbody></table></div></div>
</div></section>
<div wire:ignore.self class="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-900/50 p-4 hidden" id="billingProfileModal" tabindex="-1"><div class="mx-auto my-8 w-full max-w-lg"><div class="overflow-hidden rounded-xl bg-white text-slate-800 shadow-xl"><form wire:submit="saveBillingProfile"><div class="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-3"><h5>Billing profile</h5><button type="button" class="text-xl leading-none text-slate-500 hover:text-slate-800" data-dismiss="modal">&times;</button></div><div class="p-4"><input class="form-control ui-input mb-2" wire:model="billingLegalName" placeholder="Legal billing name"><input class="form-control ui-input mb-2" wire:model="billingTaxId" placeholder="Tax ID / TIN"><textarea class="form-control ui-input mb-2" wire:model="billingAddress" placeholder="Billing address"></textarea><input class="form-control ui-input mb-2" wire:model="billingEmail" type="email" placeholder="Billing email"><input class="form-control ui-input" wire:model="billingPhone" placeholder="Billing phone"></div><div class="flex flex-wrap justify-end gap-2 border-t border-slate-200 bg-slate-50 px-4 py-3"><button class="btn ui-button ui-button-primary">Save billing profile</button></div></form></div></div></div>
</div>
