<div class="clinic-ui ui-page">
    <h4>Stock Transfers</h4><p class="text-slate-500">Move stock between branches with dispatch and receipt confirmation.</p>
    <div class="card overflow-hidden rounded-xl border border-slate-200 bg-white"><form wire:submit="createTransfer" class="card-body p-4 flex flex-wrap -mx-2 items-end">
        <div class="mb-4 w-full md:w-3/12 px-2"><label>Destination</label><select wire:model="destinationBranchId" class="form-control ui-input"><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select>@error('destinationBranchId')<small class="text-red-700">{{ $message }}</small>@enderror</div>
        <div class="mb-4 w-full md:w-3/12 px-2"><label>Product</label><select wire:model="productId" class="form-control ui-input"><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select>@error('productId')<small class="text-red-700">{{ $message }}</small>@enderror</div>
        <div class="mb-4 w-full md:w-2/12 px-2"><label>Quantity</label><input wire:model="quantity" type="number" min="1" class="form-control ui-input"></div>
        <div class="mb-4 w-full md:w-3/12 px-2"><label>Notes</label><input wire:model="notes" class="form-control ui-input"></div>
        <div class="mb-4 w-full md:w-1/12 px-2"><button class="btn ui-button ui-button-primary">Create</button></div>
    </form></div>
    <div class="flex flex-wrap -mx-2">
        <div class="w-full lg:w-6/12 px-2"><div class="card overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><strong>Outgoing</strong></div><div class="ui-table-wrap"><table class="table ui-table ui-table-sm mb-0"><thead><tr><th>Reference</th><th>Destination</th><th>Items</th><th>Status</th><th></th></tr></thead><tbody>@forelse($outgoing as $transfer)<tr><td>{{ $transfer->transfer_number }}</td><td>{{ $transfer->destinationBranch->name }}</td><td>@foreach($transfer->items as $item){{ $item->product->name }} × {{ $item->quantity }}@if(!$loop->last)<br>@endif @endforeach</td><td>{{ str_replace('_', ' ', $transfer->status) }}</td><td>@if($transfer->status === 'draft')<button wire:click="dispatchTransfer({{ $transfer->id }})" class="btn ui-button ui-button-sm ui-button-secondary">Dispatch</button>@endif</td></tr>@empty<tr><td colspan="5" class="text-slate-500 text-center">No outgoing transfers.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="w-full lg:w-6/12 px-2"><div class="card overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="card-header border-b border-slate-200 bg-slate-50 px-4 py-2"><strong>Incoming</strong></div><div class="ui-table-wrap"><table class="table ui-table ui-table-sm mb-0"><thead><tr><th>Reference</th><th>Items</th><th>Status</th><th></th></tr></thead><tbody>@forelse($incoming as $transfer)<tr><td>{{ $transfer->transfer_number }}</td><td>@foreach($transfer->items as $item){{ $item->product->name }} × {{ $item->quantity }}@if(!$loop->last)<br>@endif @endforeach</td><td>{{ str_replace('_', ' ', $transfer->status) }}</td><td>@if($transfer->status === 'in_transit')<button wire:click="receiveTransfer({{ $transfer->id }})" class="btn ui-button ui-button-sm ui-button-primary">Receive</button>@endif</td></tr>@empty<tr><td colspan="4" class="text-slate-500 text-center">No incoming transfers.</td></tr>@endforelse</tbody></table></div></div></div>
    </div>
</div>
