<div class="p-4">
    <h4>Stock Transfers</h4><p class="text-muted">Move stock between branches with dispatch and receipt confirmation.</p>
    <div class="card"><form wire:submit="createTransfer" class="card-body row align-items-end">
        <div class="form-group col-md-3"><label>Destination</label><select wire:model="destinationBranchId" class="form-control"><option value="">Select branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select>@error('destinationBranchId')<small class="text-danger">{{ $message }}</small>@enderror</div>
        <div class="form-group col-md-3"><label>Product</label><select wire:model="productId" class="form-control"><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select>@error('productId')<small class="text-danger">{{ $message }}</small>@enderror</div>
        <div class="form-group col-md-2"><label>Quantity</label><input wire:model="quantity" type="number" min="1" class="form-control"></div>
        <div class="form-group col-md-3"><label>Notes</label><input wire:model="notes" class="form-control"></div>
        <div class="form-group col-md-1"><button class="btn btn-primary">Create</button></div>
    </form></div>
    <div class="row">
        <div class="col-lg-6"><div class="card"><div class="card-header"><strong>Outgoing</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Reference</th><th>Destination</th><th>Items</th><th>Status</th><th></th></tr></thead><tbody>@forelse($outgoing as $transfer)<tr><td>{{ $transfer->transfer_number }}</td><td>{{ $transfer->destinationBranch->name }}</td><td>@foreach($transfer->items as $item){{ $item->product->name }} × {{ $item->quantity }}@if(!$loop->last)<br>@endif @endforeach</td><td>{{ str_replace('_', ' ', $transfer->status) }}</td><td>@if($transfer->status === 'draft')<button wire:click="dispatchTransfer({{ $transfer->id }})" class="btn btn-xs btn-warning">Dispatch</button>@endif</td></tr>@empty<tr><td colspan="5" class="text-muted text-center">No outgoing transfers.</td></tr>@endforelse</tbody></table></div></div></div>
        <div class="col-lg-6"><div class="card"><div class="card-header"><strong>Incoming</strong></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Reference</th><th>Items</th><th>Status</th><th></th></tr></thead><tbody>@forelse($incoming as $transfer)<tr><td>{{ $transfer->transfer_number }}</td><td>@foreach($transfer->items as $item){{ $item->product->name }} × {{ $item->quantity }}@if(!$loop->last)<br>@endif @endforeach</td><td>{{ str_replace('_', ' ', $transfer->status) }}</td><td>@if($transfer->status === 'in_transit')<button wire:click="receiveTransfer({{ $transfer->id }})" class="btn btn-xs btn-success">Receive</button>@endif</td></tr>@empty<tr><td colspan="4" class="text-muted text-center">No incoming transfers.</td></tr>@endforelse</tbody></table></div></div></div>
    </div>
</div>
