<?php

namespace App\Services\Finance;

use App\Models\Setting;
use Symfony\Component\HttpFoundation\Response;

/**
 * CSV and PDF downloads for any business line's financial statement.
 *
 * A statement is handed over as a plain document so each line keeps its own
 * figures while sharing one layout:
 *   ['title', 'from', 'to', 'generated_by', 'generated_at',
 *    'rows' => [['type' => heading|line|total|final, 'label', 'amount' => ?float, 'note' => ?string]],
 *    'notes' => [string], 'status' => ?string]
 */
class StatementExporter
{
    public function csv(array $document, string $filename): Response
    {
        $settings = Setting::getSettings();
        // Labels include user-typed category names, so guard against spreadsheet formulas.
        $safe = static fn ($value): string => ($value = (string) $value) !== '' && preg_match('/^[=+\-@\t\r]/', $value) ? "'".$value : $value;

        return response()->streamDownload(function () use ($document, $settings, $safe) {
            $file = fopen('php://output', 'w');
            fprintf($file, chr(0xEF).chr(0xBB).chr(0xBF));
            fputcsv($file, [$document['title'], $document['from'], $document['to']]);
            fputcsv($file, [$settings->clinic_name]);
            if ($settings->clinic_address) fputcsv($file, [$safe($settings->clinic_address)]);
            if ($settings->clinic_contact || $settings->clinic_email) fputcsv($file, ['Contact', $safe($settings->clinic_contact), 'Email', $safe($settings->clinic_email)]);
            fputcsv($file, ['Generated By', $document['generated_by'], 'Currency', currency()]);
            if (! empty($document['status'])) fputcsv($file, [$document['status']]);
            foreach ($document['rows'] as $row) {
                if ($row['type'] === 'heading') fputcsv($file, []);
                fputcsv($file, [
                    $safe($row['label']),
                    isset($row['amount']) ? number_format((float) $row['amount'], 2, '.', '') : '',
                    $safe($row['note'] ?? ''),
                ]);
            }
            if (! empty($document['notes'])) {
                fputcsv($file, []);
                foreach ($document['notes'] as $note) fputcsv($file, [$safe($note)]);
            }
            fclose($file);
        }, $filename.'.csv', ['Content-Type' => 'text/csv']);
    }

    public function pdf(array $document, string $filename): Response
    {
        return \Barryvdh\DomPDF\Facade\Pdf::loadView('reports.pdf-statement', $document + ['clinicSettings' => Setting::getSettings()])
            ->setPaper('a4', 'portrait')
            ->download($filename.'.pdf');
    }

    /** The PDF layout as a web page, with a print button. */
    public function preview(array $document): \Illuminate\Contracts\View\View
    {
        return view('reports.pdf-statement', $document + ['clinicSettings' => Setting::getSettings(), 'preview' => true]);
    }
}
