<?php
namespace App\Services;
use App\Mail\SubscriptionBillingMail;
use App\Models\{BillingNotificationLog,Clinic,ClinicSubscription,PlatformInvoice,PlatformPayment,User};
use App\Support\Tenancy\TenantContext;
use Illuminate\Support\Facades\{DB,Mail};
class BillingNotificationService
{
 public function processDue():int{$count=0;Clinic::with('currentSubscription.plan')->where('status','active')->where('deployment_mode','hosted')->chunkById(100,function($clinics)use(&$count){foreach($clinics as $clinic){$s=$clinic->currentSubscription;if(!$s)continue;$today=now()->startOfDay();if($s->status==='trial'&&$s->trial_ends_at){$days=(int)$today->diffInDays($s->trial_ends_at->copy()->startOfDay(),false);if(in_array($days,[30,14,7,1,0],true))$count+=(int)$this->send($clinic,$s,null,'trial_expiry_'.$days,($days===0?"Trial ends today":"Trial ends in {$days} ".\Illuminate\Support\Str::plural("day",$days)),"Your trial ends on {$s->trial_ends_at->format('d M Y H:i T')}. Select a plan before expiry.");}if($s->status==='active'&&$s->current_period_ends_at){$days=(int)$today->diffInDays($s->current_period_ends_at->copy()->startOfDay(),false);if(in_array($days,[30,14,7,3,1],true))$count+=(int)$this->send($clinic,$s,null,'renewal_due_'.$days,"Renewal due in {$days} ".\Illuminate\Support\Str::plural("day",$days),"Your subscription renews on {$s->current_period_ends_at->format('d M Y H:i T')}.");}if($s->status==='overdue')$count+=(int)$this->send($clinic,$s,null,'overdue','Subscription expired','Your subscription has expired. Staff will be locked out on '.$s->current_period_ends_at?->copy()->addDays((int)config('subscriptions.grace_days',1))->format('d M Y H:i T').' unless you renew today.');if(in_array($s->status,['restricted','suspended'],true))$count+=(int)$this->send($clinic,$s,null,$s->status,$s->status==='restricted'?'Staff are locked out':'Clinic subscription suspended',$s->status==='restricted'?'Your subscription has not been renewed, so staff can no longer sign in. Administrators can still sign in to pay; access returns as soon as payment is confirmed.':'Operational access is suspended. Contact the platform administrator.');}});return $count;}
 public function invoiceIssued(PlatformInvoice $invoice):bool{return $this->send($invoice->clinic,$invoice->subscription,$invoice,'invoice_issued','New subscription invoice issued',"Invoice {$invoice->number} is due on {$invoice->due_date->format('d M Y H:i T')}.",[$invoice->currency.' '.number_format((float)$invoice->total,2)]);}
 public function paymentReceived(PlatformPayment $payment):bool{$invoice=$payment->invoice->loadMissing(['clinic','subscription']);return $this->send($invoice->clinic,$invoice->subscription,$invoice,'payment_received_'.$payment->id,'Subscription payment received',"Payment for invoice {$invoice->number} was recorded successfully.",[$invoice->currency.' '.number_format((float)$payment->amount,2)]);}
 private function send(Clinic $clinic,?ClinicSubscription $subscription,?PlatformInvoice $invoice,string $event,string $title,string $body,array $amount=[]):bool
 {
  $key=implode(':',[$clinic->id,$subscription?->id??0,$invoice?->id??0,$event]);
  if(BillingNotificationLog::where('deduplication_key',$key)->exists())return false;
  $admins=$this->admins($clinic);
  // Email goes to the clinic owner only (the billing email given at sign-up); Super Admins see it in the app.
  $emails=collect([OwnerMailer::ownerEmail($clinic)])->filter()->values();
  $log=BillingNotificationLog::create(['clinic_id'=>$clinic->id,'clinic_subscription_id'=>$subscription?->id,'platform_invoice_id'=>$invoice?->id,'event'=>$event,'deduplication_key'=>$key,'recipients'=>$emails->all(),'status'=>'pending']);
  try{foreach($admins as $admin)$this->inApp($clinic,$admin,$event,$title,$body,$invoice);if($emails->isEmpty()){$log->update(['status'=>'failed','error'=>'The clinic has no owner email.']);return false;}foreach($emails as $email)Mail::to($email)->send(new SubscriptionBillingMail(['subject'=>$title,'title'=>$title,'body'=>$body,'clinic_name'=>$clinic->name,'amount'=>$amount[0]??null,'invoice'=>$invoice?->number,'url'=>route('admin.subscription')]));$log->update(['status'=>'sent','sent_at'=>now()]);return true;}
  catch(\Throwable $e){$log->update(['status'=>'failed','error'=>$e->getMessage()]);report($e);return false;}
 }
 private function admins(Clinic $clinic){return $clinic->users()->wherePivot('status','active')->where(function($q){$q->where('clinic_user.clinic_role','like','%Super Admin%')->orWhereHas('roles',fn($r)=>$r->where('name','Super Admin'));})->get();}
 private function inApp(Clinic $clinic,User $admin,string $event,string $title,string $body,?PlatformInvoice $invoice):void{$branch=$admin->branches()->where('branches.clinic_id',$clinic->id)->wherePivot('status','active')->orderByDesc('branch_user.is_default')->first()?:$clinic->branches()->where('is_active',true)->orderByDesc('is_default')->first();if(!$branch)return;$context=app(TenantContext::class);$context->set($admin,$clinic,$branch,[$branch->id]);NotificationService::send($admin->id,'subscription.'.$event,$title,$body,'fas fa-credit-card','text-warning',route('admin.subscription'),['invoice_id'=>$invoice?->id]);}
}
