<?php
namespace App\Services;
use App\Models\{PlatformCreditNote,PlatformInvoice,PlatformPayment,PlatformPaymentRefund};
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
class BillingAdjustmentService
{
 public function credit(PlatformInvoice $invoice,float $amount,string $reason,?int $operator):PlatformCreditNote{return DB::transaction(function()use($invoice,$amount,$reason,$operator){$invoice=PlatformInvoice::lockForUpdate()->findOrFail($invoice->id);if($invoice->voided_at||$amount<=0||$amount>$invoice->balance())throw ValidationException::withMessages(['adjustmentAmount'=>'Credit must be positive and cannot exceed the invoice balance.']);$note=PlatformCreditNote::create(['number'=>'CN-'.now()->format('YmHis').'-'.Str::upper(Str::random(4)),'clinic_id'=>$invoice->clinic_id,'platform_invoice_id'=>$invoice->id,'amount'=>$amount,'currency'=>$invoice->currency,'reason'=>$reason,'issued_by'=>$operator,'issued_at'=>now()]);$credited=round((float)$invoice->credited_amount+$amount,2);$invoice->credited_amount=$credited;$invoice->status=$invoice->balance()-$amount<=0?'credited':((float)$invoice->amount_paid>0?'partial':'unpaid');$invoice->save();return $note;});}
 public function refund(PlatformPayment $payment,float $amount,string $method,string $reason,?string $reference,?int $operator):PlatformPaymentRefund{return DB::transaction(function()use($payment,$amount,$method,$reason,$reference,$operator){$payment=PlatformPayment::with('invoice')->lockForUpdate()->findOrFail($payment->id);$refunded=(float)$payment->refunds()->sum('amount');if($amount<=0||$amount>(float)$payment->amount-$refunded)throw ValidationException::withMessages(['adjustmentAmount'=>'Refund cannot exceed the unrefunded payment amount.']);$invoice=PlatformInvoice::lockForUpdate()->findOrFail($payment->platform_invoice_id);$refund=PlatformPaymentRefund::create(['number'=>'RF-'.now()->format('YmHis').'-'.Str::upper(Str::random(4)),'clinic_id'=>$invoice->clinic_id,'platform_invoice_id'=>$invoice->id,'platform_payment_id'=>$payment->id,'amount'=>$amount,'currency'=>$invoice->currency,'method'=>$method,'reference'=>$reference,'reason'=>$reason,'refunded_by'=>$operator,'refunded_at'=>now()]);$invoice->refunded_amount=round((float)$invoice->refunded_amount+$amount,2);$invoice->status=$invoice->balance()+$amount>0?'partial':'paid';$invoice->save();return $refund;});}
 public function void(PlatformInvoice $invoice,string $reason,?int $operator):PlatformInvoice{return DB::transaction(function()use($invoice,$reason,$operator){$invoice=PlatformInvoice::lockForUpdate()->findOrFail($invoice->id);if((float)$invoice->amount_paid>0||(float)$invoice->credited_amount>0)throw ValidationException::withMessages(['adjustmentReason'=>'Paid or credited invoices cannot be voided; issue a refund or credit note instead.']);$invoice->update(['status'=>'void','voided_at'=>now(),'void_reason'=>$reason,'voided_by'=>$operator]);return $invoice;});}
}
