<?php
namespace App\Services;
use App\Models\{Clinic,ClinicOffboardingRequest,PlatformInvoice};
use Illuminate\Support\Facades\{DB,Storage};
use Illuminate\Validation\ValidationException;
class ClinicOffboardingService
{
 public function request(Clinic $clinic,string $timing,string $reason,int $requester):ClinicOffboardingRequest
 {abort_unless(in_array($timing,['period_end','immediate'],true),422);$subscription=$clinic->currentSubscription;abort_unless($subscription,422,'Clinic has no current subscription.');abort_if(ClinicOffboardingRequest::where('clinic_id',$clinic->id)->whereIn('status',['pending_approval','scheduled','retention'])->exists(),422,'An offboarding request is already active.');$effective=$timing==='immediate'?now():($subscription->current_period_ends_at??now());return ClinicOffboardingRequest::create(['clinic_id'=>$clinic->id,'clinic_subscription_id'=>$subscription->id,'timing'=>$timing,'status'=>$timing==='immediate'?'pending_approval':'scheduled','reason'=>$reason,'effective_at'=>$effective,'requested_by'=>$requester,'checklist'=>$this->checklist($clinic)]);}
 public function approve(ClinicOffboardingRequest $request,int $approver,string $notes):ClinicOffboardingRequest
 {if($request->status!=='pending_approval')throw ValidationException::withMessages(['offboarding'=>'Only pending immediate cancellations can be approved.']);if($request->requested_by===$approver)throw ValidationException::withMessages(['offboarding'=>'The requester cannot approve immediate cancellation.']);$request->update(['status'=>'scheduled','approved_by'=>$approver,'approved_at'=>now(),'review_notes'=>$notes]);return $this->process($request);}
 public function processDue():int{$count=0;ClinicOffboardingRequest::where('status','scheduled')->where('effective_at','<=',now())->each(function($r)use(&$count){$this->process($r);$count++;});ClinicOffboardingRequest::where('status','retention')->where('retention_until','<=',now())->each(function($r)use(&$count){$this->complete($r);$count++;});return $count;}
 public function process(ClinicOffboardingRequest $request):ClinicOffboardingRequest
 {return DB::transaction(function()use($request){$request=ClinicOffboardingRequest::lockForUpdate()->findOrFail($request->id);if($request->status!=='scheduled'||$request->effective_at->isFuture())return $request;$blockers=$this->blockers($request->clinic);if($blockers){$request->update(['status'=>'blocked','blockers'=>$blockers,'checklist'=>$this->checklist($request->clinic)]);return $request->refresh();}$evidence=$this->exportEvidence($request);$until=now()->addDays((int)config('subscriptions.offboarding_retention_days',30));$request->subscription->update(['status'=>'cancelled','cancelled_at'=>now(),'status_changed_at'=>now(),'change_reason'=>$request->reason]);$request->clinic->update(['status'=>'suspended']);$request->update(['status'=>'retention','retention_until'=>$until,'export_path'=>$evidence['path'],'export_checksum'=>$evidence['checksum'],'checklist'=>$this->checklist($request->clinic)+['export_created'=>true,'financial_clearance'=>true]]);$this->notify($request,'Clinic subscription cancelled',"The clinic is read-only during the retention period ending {$until->format('d M Y')}.");return $request->refresh();});}
 public function reverse(ClinicOffboardingRequest $request,int $operator,string $reason):ClinicOffboardingRequest
 {if($request->status!=='retention'||!$request->retention_until?->isFuture())throw ValidationException::withMessages(['offboarding'=>'Only an active retention-period cancellation can be reversed.']);return DB::transaction(function()use($request,$operator,$reason){$request->subscription->update(['status'=>'active','cancelled_at'=>null,'status_changed_at'=>now(),'change_reason'=>$reason]);$request->clinic()->withTrashed()->first()->restore();$request->clinic()->withTrashed()->first()->update(['status'=>'active']);$request->update(['status'=>'reversed','reversed_by'=>$operator,'reversed_at'=>now(),'review_notes'=>trim(($request->review_notes??'')."\nReversal: ".$reason)]);return $request->refresh();});}
 private function complete(ClinicOffboardingRequest $request):void{DB::transaction(function()use($request){$clinic=$request->clinic;$request->update(['status'=>'completed','completed_at'=>now()]);$clinic->delete();});}
 private function blockers(Clinic $clinic):array{$items=[];$outstanding=PlatformInvoice::where('clinic_id',$clinic->id)->whereNotIn('status',['paid','void','credited'])->where('source','!=','sms_bundle')->get()->sum(fn($i)=>$i->balance());if($outstanding>0)$items[]=['code'=>'OUTSTANDING_BALANCE','message'=>'Outstanding invoice balance must be settled or adjusted.','amount'=>$outstanding];return $items;}
 private function checklist(Clinic $clinic):array{return ['subscription_present'=>(bool)$clinic->currentSubscription,'default_branch'=>(bool)$clinic->branches()->where('is_default',true)->exists(),'super_admin'=>(bool)$clinic->users()->wherePivot('status','active')->whereHas('roles',fn($q)=>$q->where('name','Super Admin'))->exists(),'financial_clearance'=>count($this->blockers($clinic))===0,'export_created'=>false];}
 private function exportEvidence(ClinicOffboardingRequest $request):array{$clinic=$request->clinic;$payload=['generated_at'=>now()->toIso8601String(),'clinic'=>['uuid'=>$clinic->uuid,'name'=>$clinic->name,'slug'=>$clinic->slug],'request_uuid'=>$request->uuid,'reason'=>$request->reason,'counts'=>['branches'=>$clinic->branches()->count(),'users'=>$clinic->users()->count(),'patients'=>DB::table('patients')->where('clinic_id',$clinic->id)->count(),'consultations'=>DB::table('consultations')->where('clinic_id',$clinic->id)->count(),'sales'=>DB::table('sales')->where('clinic_id',$clinic->id)->count(),'invoices'=>$clinic->invoices()->count()]];$json=json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);$path='offboarding/'.$clinic->uuid.'/'.$request->uuid.'.json';Storage::disk('local')->put($path,$json);return ['path'=>$path,'checksum'=>hash('sha256',$json)];}
 private function notify(ClinicOffboardingRequest $request,string $title,string $body):void{$clinic=$request->clinic;$branch=$clinic->branches()->where('is_default',true)->first()??$clinic->branches()->first();if(!$branch)return;$ids=$clinic->users()->wherePivot('status','active')->whereHas('roles',fn($q)=>$q->where('name','Super Admin'))->pluck('users.id');foreach($ids as $id)DB::table('app_notifications')->insert(['clinic_id'=>$clinic->id,'branch_id'=>$branch->id,'user_id'=>$id,'type'=>'subscription.offboarding','title'=>$title,'body'=>$body,'icon'=>'fas fa-user-slash','icon_color'=>'text-danger','action_url'=>route('admin.subscription'),'data'=>json_encode(['offboarding_uuid'=>$request->uuid]),'created_at'=>now(),'updated_at'=>now()]);}
}
