<?php
namespace App\Services;
use App\Models\DeploymentReadinessRun;
use Illuminate\Support\Facades\{Cache,DB,File,Schema,Storage};
use Illuminate\Support\Str;
class DeploymentReadinessService {
 public function run(bool $persist=true,?int $userId=null):array{
  $checks=[];$add=function($key,$category,$label,$passed,$severity='critical',$detail='',$remediation='')use(&$checks){$checks[$key]=compact('category','label','passed','severity','detail','remediation');};
  $production=app()->environment('production');$add('environment','Environment','Production environment',$production,'critical','APP_ENV='.app()->environment(),'Set APP_ENV=production on the hosted server.');
  $add('debug','Environment','Debug mode disabled',!config('app.debug'),'critical','APP_DEBUG='.(config('app.debug')?'true':'false'),'Set APP_DEBUG=false and clear configuration cache.');
  $add('app_key','Security','Application encryption key configured',(bool)config('app.key'),'critical',config('app.key')?'Configured':'Missing','Generate and securely retain APP_KEY.');
  $url=(string)config('app.url');$add('https','Security','HTTPS application URL',str_starts_with(strtolower($url),'https://'),'critical',$url,'Configure TLS and set APP_URL to the HTTPS domain.');
  $add('tenancy','Tenancy','Tenant context enabled',(bool)config('tenancy.enabled'),'critical','TENANCY_CONTEXT_ENABLED='.(config('tenancy.enabled')?'true':'false'),'Enable only after reconciliation and pilot sign-off.');
  $dbReachable=false;try{$database=DB::connection()->getDatabaseName();DB::select('SELECT 1');$dbReachable=true;$add('database','Database','Database reachable',!str_ends_with($database,'_testing'),'critical',$database,'Use a dedicated non-testing production database.');$username=(string)config('database.connections.'.config('database.default').'.username');$add('database_user','Security','Least-privilege database user',!in_array(strtolower($username),['root','sa','postgres'],true),'critical',$username,'Create a dedicated application database account without server-wide privileges.');}catch(\Throwable $e){$add('database','Database','Database reachable',false,'critical',$e->getMessage(),'Correct database host, credentials and grants.');}
  $migrationFiles=collect(File::glob(database_path('migrations/*.php')))->map(fn($p)=>pathinfo($p,PATHINFO_FILENAME));$ran=$dbReachable&&Schema::hasTable('migrations')?DB::table('migrations')->pluck('migration'):collect();$pending=$migrationFiles->diff($ran)->values();$add('migrations','Database','No pending migrations',$pending->isEmpty(),'critical',$pending->isEmpty()?'All migrations applied':$pending->take(5)->implode(', '),'Run php artisan migrate --force after taking a verified backup.');
  $queue=(string)config('queue.default');$add('queue_driver','Runtime','Persistent queue configured',!in_array($queue,['sync','null'],true),'critical',$queue,'Use database, Redis, SQS or another persistent queue.');$queueSeen=Cache::get('platform.queue_worker_last_seen');$queueFresh=$queueSeen&&abs(now()->diffInMinutes($queueSeen))<=5;$add('queue_worker','Runtime','Queue worker heartbeat',$queueFresh,'critical',$queueSeen?'Last seen '.now()->parse($queueSeen)->diffForHumans():'Never observed','Run a supervised queue worker for imports, SMS/WhatsApp messages and default queues.');
  $session=(string)config('session.driver');$add('session_driver','Runtime','Persistent session storage',!in_array($session,['array','cookie'],true),'critical',$session,'Use database, Redis or file sessions; avoid array/cookie sessions for hosted multi-tenant use.');
  $cache=(string)config('cache.default');$add('cache_driver','Runtime','Shared persistent cache',!in_array($cache,['array','null'],true),'warning',$cache,'Use Redis, database or file cache so worker and scheduler heartbeats are visible.');
  $log=(string)config('logging.default');$add('logging','Observability','Persistent application logging',!in_array($log,['null','errorlog'],true),'warning',$log,'Use daily, stack or a centralized production log channel.');
  $scheduler=Cache::get('platform.scheduler_last_seen')??($dbReachable&&Schema::hasTable('system_health_statuses')?DB::table('system_health_statuses')->where('key','scheduler')->max('checked_at'):null);$schedulerFresh=$scheduler&&abs(now()->diffInMinutes($scheduler))<=5;$add('scheduler','Runtime','Scheduler heartbeat',$schedulerFresh,'critical',$scheduler?'Last seen '.now()->parse($scheduler)->diffForHumans():'Never recorded','Configure cron or Task Scheduler to run schedule:run every minute.');
  $failed=$dbReachable&&Schema::hasTable('failed_jobs')?DB::table('failed_jobs')->count():0;$add('failed_jobs','Runtime','No failed queue jobs',$failed===0,'warning',"{$failed} failed job(s)",'Review and retry or forget resolved failed jobs.');
  foreach(['storage'=>storage_path(),'cache'=>storage_path('framework/cache'),'sessions'=>storage_path('framework/sessions'),'views'=>storage_path('framework/views')] as $key=>$path)$add('writable_'.$key,'Storage',ucfirst($key).' path writable',is_dir($path)&&is_writable($path),'critical',$path,'Grant the web and worker service accounts write access.');
  $free=@disk_free_space(storage_path());$minimum=2*1024*1024*1024;$add('disk_space','Storage','At least 2 GB free storage',$free!==false&&$free>=$minimum,'critical',$free===false?'Unavailable':round($free/1073741824,2).' GB free','Free disk space or expand storage before deployment and backup creation.');
  // Hosted installs schedule no app backups (their disk is wiped on every deploy); the database provider keeps them.
  if(config('tenancy.enabled')){$add('backup','Recovery','Database backups',true,'warning','Hosted: kept by the database provider, not the app. Check Laravel Cloud → Database → Backups.','');}else{
  try{$disk=Storage::disk('backups');$files=collect($disk->allFiles())->filter(fn($f)=>preg_match('/\.(zip|sql)$/i',$f));$latest=$files->map(fn($f)=>$disk->lastModified($f))->max();$hours=$latest?abs(now()->diffInHours(now()->createFromTimestamp($latest))):null;$add('backup','Recovery','Backup less than 24 hours old',$hours!==null&&$hours<=24,$hours!==null&&$hours<=48?'warning':'critical',$hours===null?'No backup found':'Latest backup '.round($hours,1).' hour(s) old','Run and verify a full backup; keep an off-server copy.');}catch(\Throwable $e){$add('backup','Recovery','Backup storage readable',false,'critical',$e->getMessage(),'Correct backup disk configuration and permissions.');}
  }
  $mailer=(string)config('mail.default');$smtp=config("mail.mailers.{$mailer}");$mailReady=!in_array($mailer,['array','log'],true)&&is_array($smtp)&&!empty($smtp['host'])&&!empty($smtp['username']);$add('mail','Communications','Production mail transport configured',$mailReady,'warning',$mailer,$mailReady?'':'Configure authenticated SMTP or a transactional mail provider.');$smsReady=filled(config('services.eazisms.url'))&&filled(config('services.eazisms.key'));$add('platform_sms','Communications','Platform SMS gateway configured',$smsReady,'warning',$smsReady?'EazismsPro, default sender '.(config('services.eazisms.default_sender')?:'account default'):'Missing credentials',$smsReady?'':'Set EAZISMS_API_URL, EAZISMS_API_KEY and EAZISMS_DEFAULT_SENDER; hosted clinics cannot send SMS without them.');
  $platformAdmins=$dbReachable&&Schema::hasTable('users')?DB::table('users')->where('is_platform_admin',1)->count():0;$add('platform_admin','Security','Platform administrator exists',$platformAdmins>0,'critical',"{$platformAdmins} account(s)",'Create and verify at least one developer/platform administrator.');
  $failedCritical=collect($checks)->filter(fn($c)=>!$c['passed']&&$c['severity']==='critical')->count();$warnings=collect($checks)->filter(fn($c)=>!$c['passed']&&$c['severity']==='warning')->count();$passed=collect($checks)->where('passed',true)->count();$report=['ready'=>$failedCritical===0,'status'=>$failedCritical?'blocked':($warnings?'warning':'ready'),'generated_at'=>now()->toIso8601String(),'environment'=>app()->environment(),'host'=>gethostname()?:null,'summary'=>['passed'=>$passed,'warnings'=>$warnings,'failed'=>$failedCritical,'total'=>count($checks)],'checks'=>$checks];
  if($persist&&$dbReachable&&Schema::hasTable('deployment_readiness_runs'))DeploymentReadinessRun::create(['uuid'=>(string)Str::uuid(),'run_by'=>$userId,'environment'=>$report['environment'],'status'=>$report['status'],'ready'=>$report['ready'],'passed_checks'=>$passed,'warning_checks'=>$warnings,'failed_checks'=>$failedCritical,'report'=>$report,'host'=>$report['host'],'completed_at'=>now()]);return $report;
 }
}
