<?php
namespace App\Services;
use App\Models\{ClinicSubscription,PlatformInvoice,SubscriptionCollectionCase,SubscriptionCollectionNote};
use Illuminate\Support\Facades\DB;
class SubscriptionCollectionService
{
 public function agingBucket(PlatformInvoice $invoice):string{$days=$invoice->due_date->diffInDays(now()->startOfDay(),false);return $days<=0?'current':($days<=30?'1-30':($days<=60?'31-60':($days<=90?'61-90':'90+')));}
 public function synchronize():array{$opened=0;$resolved=0;PlatformInvoice::with('subscription')->whereNotIn('status',['paid','void','credited'])->where('source','!=','sms_bundle')->where('due_date','<',now()->startOfDay())->chunkById(100,function($items)use(&$opened){foreach($items as $invoice){$case=SubscriptionCollectionCase::firstOrCreate(['platform_invoice_id'=>$invoice->id],['clinic_id'=>$invoice->clinic_id,'clinic_subscription_id'=>$invoice->clinic_subscription_id,'status'=>'open','aging_bucket'=>$this->agingBucket($invoice)]);if($case->wasRecentlyCreated)$opened++;else$case->update(['aging_bucket'=>$this->agingBucket($invoice)]);}});SubscriptionCollectionCase::with('invoice')->whereIn('status',['open','promise'])->chunkById(100,function($cases)use(&$resolved){foreach($cases as $case)if(!$case->invoice||$case->invoice->balance()<=0||$case->invoice->status==='void'){$case->update(['status'=>'resolved','resolved_at'=>now()]);$resolved++;}});return compact('opened','resolved');}
 public function note(SubscriptionCollectionCase $case,string $method,string $note,?int $userId):SubscriptionCollectionNote{$entry=$case->notes()->create(['user_id'=>$userId,'contact_method'=>$method,'note'=>$note,'contacted_at'=>now()]);$case->update(['last_contacted_at'=>now()]);return $entry;}
 public function promise(SubscriptionCollectionCase $case,string $date,float $amount,string $note,?int $userId):void{DB::transaction(function()use($case,$date,$amount,$note,$userId){abort_if($amount<=0||$amount>$case->invoice->balance(),422,'Promise amount must not exceed the outstanding balance.');$case->update(['status'=>'promise','promised_payment_date'=>$date,'promised_amount'=>$amount,'last_contacted_at'=>now()]);$this->note($case,'promise',$note,$userId);});}
 public function reinstate(ClinicSubscription $subscription,string $reason):ClinicSubscription{abort_unless(in_array($subscription->status,['restricted','suspended','overdue'],true),422,'Only delinquent subscriptions can be reinstated.');$subscription->update(['status'=>'active','status_changed_at'=>now(),'restricted_at'=>null,'suspended_at'=>null,'grace_ends_at'=>null,'current_period_starts_at'=>now(),'current_period_ends_at'=>$subscription->billing_interval==='yearly'?now()->addYear():now()->addMonth(),'change_reason'=>$reason]);return $subscription;}
 public function bulkGenerate():int{$count=0;ClinicSubscription::with(['clinic','plan'])->whereIn('status',['active','trial','overdue'])->whereNotNull('current_period_ends_at')->where('current_period_ends_at','<=',now()->addDays(30))->chunkById(100,function($items)use(&$count){foreach($items as $subscription){$invoice=app(SubscriptionBillingService::class)->invoiceFor($subscription);if($invoice->wasRecentlyCreated)$count++;}});return $count;}
}
