<?php
namespace App\Services;
use App\Models\{Clinic,ClinicSubscription,PlatformCreditNote,PlatformInvoice,PlatformPayment,PlatformPaymentRefund,SubscriptionChange,SubscriptionCollectionCase,SubscriptionPlan};
use Carbon\CarbonInterface;
class SubscriptionAnalyticsService
{
 public function report(CarbonInterface $from,CarbonInterface $to,array $filters=[]):array
 {
  $clinicId=$filters['clinic_id']??null;$planId=$filters['plan_id']??null;$status=$filters['status']??null;
  $latestIds=ClinicSubscription::query()->selectRaw('MAX(id)')->groupBy('clinic_id');
  $subs=ClinicSubscription::with(['clinic','plan'])->whereIn('id',$latestIds)->when($clinicId,fn($q)=>$q->where('clinic_id',$clinicId))->when($planId,fn($q)=>$q->where('subscription_plan_id',$planId))->when($status,fn($q)=>$q->where('status',$status))->get()->when($filters['product']??null,fn($c,$product)=>$c->filter(fn($s)=>\App\Support\PlanProduct::productOf($s->feature_snapshot)===$product))->keyBy('clinic_id');
  $clinicIds=$subs->pluck('clinic_id');$invoiceQuery=PlatformInvoice::with('clinic')->whereIn('clinic_id',$clinicIds)->whereBetween('created_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()]);$invoices=$invoiceQuery->get();
  $payments=PlatformPayment::whereHas('invoice',fn($q)=>$q->whereIn('clinic_id',$clinicIds))->whereBetween('paid_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->sum('amount');
  $refunds=PlatformPaymentRefund::whereIn('clinic_id',$clinicIds)->whereBetween('refunded_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->sum('amount');$credits=PlatformCreditNote::whereIn('clinic_id',$clinicIds)->whereBetween('issued_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->sum('amount');
  $mrr=$subs->where('status','active')->sum(fn($s)=>$s->billing_interval==='yearly'?(float)data_get($s->pricing_snapshot,'annual_price',0)/12:(float)data_get($s->pricing_snapshot,'base_price',0));
  $trialClinicIds=ClinicSubscription::whereIn('clinic_id',$clinicIds)->where('status','trial')->where('created_at','<=',$to)->pluck('clinic_id')->unique();$converted=$trialClinicIds->filter(fn($id)=>ClinicSubscription::where('clinic_id',$id)->where('status','active')->where('created_at','<=',$to)->exists())->count();
  $changes=SubscriptionChange::with(['fromPlan','toPlan'])->whereIn('clinic_id',$clinicIds)->where('status','applied')->whereBetween('applied_at',[$from,$to])->get();$upgrades=$changes->filter(fn($c)=>(float)$c->toPlan->base_price>(float)$c->fromPlan->base_price)->count();$downgrades=$changes->filter(fn($c)=>(float)$c->toPlan->base_price<(float)$c->fromPlan->base_price)->count();
  $churned=$subs->whereIn('status',['cancelled','suspended'])->filter(fn($s)=>$s->status_changed_at?->between($from,$to))->count();$starting=max(1,ClinicSubscription::whereIn('clinic_id',$clinicIds)->where('created_at','<',$from)->distinct('clinic_id')->count('clinic_id'));
  $renewals=$subs->filter(fn($s)=>$s->current_period_ends_at?->between(now(),now()->addDays(90)));$promises=SubscriptionCollectionCase::whereIn('clinic_id',$clinicIds)->where('status','promise')->whereBetween('promised_payment_date',[now()->toDateString(),now()->addDays(90)->toDateString()])->sum('promised_amount');
  $byPlan=$subs->groupBy(fn($s)=>data_get($s->plan_snapshot,'name',$s->plan?->name??'Unknown'))->map(fn($items)=>['clinics'=>$items->count(),'mrr'=>$items->where('status','active')->sum(fn($s)=>$s->billing_interval==='yearly'?(float)data_get($s->pricing_snapshot,'annual_price',0)/12:(float)data_get($s->pricing_snapshot,'base_price',0))])->sortByDesc('mrr');
  // Aging covers the same invoices as the Outstanding figure, bucketed by days past the due date.
  $monthly=fn($s)=>$s->billing_interval==='yearly'?(float)data_get($s->pricing_snapshot,'annual_price',0)/12:(float)data_get($s->pricing_snapshot,'base_price',0);
  $byProduct=collect(\App\Support\PlanProduct::PRODUCTS)->map(fn($label,$key)=>['label'=>$label,'clinics'=>0,'mrr'=>0.0])->all();foreach($subs as $s){$k=\App\Support\PlanProduct::productOf($s->feature_snapshot);$byProduct[$k]['clinics']++;if($s->status==='active')$byProduct[$k]['mrr']+=$monthly($s);}
  $aging=collect(['current'=>0,'1-30'=>0,'31-60'=>0,'61-90'=>0,'90+'=>0]);$invoices->whereIn('status',['unpaid','partial'])->each(function($i)use($aging){$days=$i->due_date&&$i->due_date->lt(today())?(int)$i->due_date->diffInDays(today()):0;$bucket=$days===0?'current':($days<=30?'1-30':($days<=60?'31-60':($days<=90?'61-90':'90+')));$aging->put($bucket,$aging->get($bucket)+$i->balance());});
  // Month-by-month invoiced vs collected for the trend chart.
  $trend=collect();for($m=$from->copy()->startOfMonth();$m->lte($to);$m->addMonth())$trend->put($m->format('Y-m'),['label'=>$m->format('M y'),'invoiced'=>0.0,'collected'=>0.0]);
  $invoices->where('status','!=','void')->each(function($i)use($trend){$k=$i->created_at->format('Y-m');if($trend->has($k))$trend->put($k,array_merge($trend[$k],['invoiced'=>$trend[$k]['invoiced']+(float)$i->total]));});
  PlatformPayment::whereHas('invoice',fn($q)=>$q->whereIn('clinic_id',$clinicIds))->whereBetween('paid_at',[$from->copy()->startOfDay(),$to->copy()->endOfDay()])->get(['amount','paid_at'])->each(function($p)use($trend){$k=$p->paid_at->format('Y-m');if($trend->has($k))$trend->put($k,array_merge($trend[$k],['collected'=>$trend[$k]['collected']+(float)$p->amount]));});
  $activeCount=$subs->where('status','active')->count();
  return ['from'=>$from,'to'=>$to,'subscriptions'=>$subs,'invoices'=>$invoices,'metrics'=>['mrr'=>$mrr,'arr'=>$mrr*12,'invoiced'=>$invoices->where('status','!=','void')->sum('total'),'collected'=>(float)$payments,'refunded'=>(float)$refunds,'credited'=>(float)$credits,'net_collections'=>(float)$payments-(float)$refunds,'outstanding'=>$invoices->where('status','!=','void')->sum(fn($i)=>$i->balance()),'trials'=>$trialClinicIds->count(),'converted'=>$converted,'conversion_rate'=>$trialClinicIds->count()?round($converted/$trialClinicIds->count()*100,1):0,'upgrades'=>$upgrades,'downgrades'=>$downgrades,'churned'=>$churned,'churn_rate'=>round($churned/$starting*100,1),'renewals_90'=>$renewals->count(),'renewal_value'=>$renewals->sum(fn($s)=>$s->billing_interval==='yearly'?(float)data_get($s->pricing_snapshot,'annual_price',0):(float)data_get($s->pricing_snapshot,'base_price',0)),'promises_90'=>(float)$promises,'active_clinics'=>$activeCount,'trial_clinics'=>$subs->where('status','trial')->count(),'arpa'=>$activeCount?$mrr/$activeCount:0,'collection_rate'=>($inv=$invoices->where('status','!=','void')->sum('total'))>0?round((float)$payments/$inv*100,1):0],'by_plan'=>$byPlan,'by_product'=>collect($byProduct),'aging'=>$aging,'trend'=>$trend->values(),'renewals'=>$renewals->sortBy('current_period_ends_at')->values()];
 }
}
