<?php
namespace App\Services;
use App\Models\{ClinicSubscription,PlatformInvoice,PlatformPayment,SubscriptionApprovalRequest};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class SubscriptionApprovalService
{
 private const ACTIONS=['credit_note','payment_refund','invoice_void','subscription_reinstate'];
 public function request(string $action,string $targetType,int $targetId,?int $clinicId,array $payload,string $reason,int $requesterId):SubscriptionApprovalRequest
 {abort_unless(in_array($action,self::ACTIONS,true),422,'Unsupported approval action.');abort_if(SubscriptionApprovalRequest::where(['action'=>$action,'target_type'=>$targetType,'target_id'=>$targetId])->where('status','pending')->where('expires_at','>',now())->exists(),422,'An approval request is already pending for this record.');$canonical=$this->canonical($action,$targetType,$targetId,$clinicId,$payload);return SubscriptionApprovalRequest::create(['clinic_id'=>$clinicId,'action'=>$action,'target_type'=>$targetType,'target_id'=>$targetId,'payload'=>$payload,'payload_hash'=>$this->sign($canonical),'reason'=>$reason,'status'=>'pending','requested_by'=>$requesterId,'expires_at'=>now()->addDays((int)config('subscriptions.approval_expiry_days',7))]);}
 public function approve(SubscriptionApprovalRequest $request,int $reviewerId,string $notes):SubscriptionApprovalRequest
 {$this->expireIfNeeded($request);return DB::transaction(function()use($request,$reviewerId,$notes){$request=SubscriptionApprovalRequest::lockForUpdate()->findOrFail($request->id);$this->assertReviewable($request,$reviewerId);$canonical=$this->canonical($request->action,$request->target_type,$request->target_id,$request->clinic_id,$request->payload);abort_unless(hash_equals($request->payload_hash,$this->sign($canonical)),409,'Approval payload integrity verification failed.');$this->execute($request,$reviewerId);$request->update(['status'=>'approved','reviewed_by'=>$reviewerId,'review_notes'=>$notes,'reviewed_at'=>now(),'executed_at'=>now()]);return $request->refresh();});}
 public function reject(SubscriptionApprovalRequest $request,int $reviewerId,string $notes):SubscriptionApprovalRequest
 {$this->expireIfNeeded($request);return DB::transaction(function()use($request,$reviewerId,$notes){$request=SubscriptionApprovalRequest::lockForUpdate()->findOrFail($request->id);$this->assertReviewable($request,$reviewerId);$request->update(['status'=>'rejected','reviewed_by'=>$reviewerId,'review_notes'=>$notes,'reviewed_at'=>now()]);return $request->refresh();});}
 private function execute(SubscriptionApprovalRequest $r,int $reviewerId):void{$p=$r->payload;$adjust=app(BillingAdjustmentService::class);match($r->action){'credit_note'=>$adjust->credit(PlatformInvoice::findOrFail($r->target_id),(float)$p['amount'],$r->reason,$reviewerId),'payment_refund'=>$adjust->refund(PlatformPayment::findOrFail($r->target_id),(float)$p['amount'],$p['method'],$r->reason,$p['reference']??null,$reviewerId),'invoice_void'=>$adjust->void(PlatformInvoice::findOrFail($r->target_id),$r->reason,$reviewerId),'subscription_reinstate'=>app(SubscriptionCollectionService::class)->reinstate(ClinicSubscription::findOrFail($r->target_id),$r->reason)};}
 private function assertReviewable(SubscriptionApprovalRequest $r,int $reviewerId):void{if($r->status!=='pending')throw ValidationException::withMessages(['approval'=>'This request was already reviewed.']);if($r->requested_by===$reviewerId)throw ValidationException::withMessages(['approval'=>'The requester cannot approve or reject their own action.']);}
 private function expireIfNeeded(SubscriptionApprovalRequest $r):void{if($r->status==='pending'&&$r->expires_at->isPast()){$r->update(['status'=>'expired']);throw ValidationException::withMessages(['approval'=>'This approval request has expired.']);}}
 private function canonical(string $action,string $targetType,int $targetId,?int $clinicId,array $payload):string{ksort($payload);return json_encode(compact('action','targetType','targetId','clinicId','payload'),JSON_UNESCAPED_SLASHES);}
 private function sign(string $value):string{return hash_hmac('sha256',$value,(string)config('app.key'));}
}
