<?php
namespace Tests\Feature;
use App\Models\{Clinic,ClinicSubscription,PlatformInvoice,PlatformPayment,SubscriptionPlan};
use App\Services\SubscriptionAnalyticsService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Livewire\Livewire;
use App\Livewire\Platform\SubscriptionAnalyticsComponent;
class SubscriptionAnalyticsTest extends TestCase
{
 use RefreshDatabase;
 public function test_report_calculates_recurring_revenue_collections_and_forecast():void{$clinic=Clinic::create(['name'=>'Analytics Clinic','slug'=>'analytics-clinic']);$plan=SubscriptionPlan::create(['name'=>'Pro','code'=>'analytics-pro','base_price'=>120,'annual_price'=>1200,'billing_interval'=>'monthly']);$subscription=ClinicSubscription::create(['clinic_id'=>$clinic->id,'subscription_plan_id'=>$plan->id,'status'=>'active','billing_interval'=>'monthly','current_period_starts_at'=>now(),'current_period_ends_at'=>now()->addDays(30)]);$invoice=PlatformInvoice::create(['number'=>'INV-ANALYTICS','clinic_id'=>$clinic->id,'clinic_subscription_id'=>$subscription->id,'period_start'=>now(),'period_end'=>now()->addMonth(),'due_date'=>now()->addWeek(),'subtotal'=>120,'tax'=>0,'total'=>120,'amount_paid'=>80,'currency'=>'GHS','status'=>'partial']);PlatformPayment::create(['platform_invoice_id'=>$invoice->id,'amount'=>80,'method'=>'bank_transfer','status'=>'confirmed','paid_at'=>now()]);$report=app(SubscriptionAnalyticsService::class)->report(now()->startOfMonth(),now()->endOfMonth());$this->assertSame(120.0,$report['metrics']['mrr']);$this->assertSame(1440.0,$report['metrics']['arr']);$this->assertSame(80.0,$report['metrics']['collected']);$this->assertSame(40.0,$report['metrics']['outstanding']);$this->assertSame(1,$report['metrics']['renewals_90']);$this->assertSame(120.0,$report['by_plan']['Pro']['mrr']);}
 public function test_clinic_filter_excludes_other_tenants():void{$first=Clinic::create(['name'=>'First','slug'=>'analytics-first']);$second=Clinic::create(['name'=>'Second','slug'=>'analytics-second']);$plan=SubscriptionPlan::create(['name'=>'Basic','code'=>'analytics-basic','base_price'=>50,'billing_interval'=>'monthly']);foreach([$first,$second] as $clinic)ClinicSubscription::create(['clinic_id'=>$clinic->id,'subscription_plan_id'=>$plan->id,'status'=>'active','billing_interval'=>'monthly']);$report=app(SubscriptionAnalyticsService::class)->report(now()->startOfYear(),now(),['clinic_id'=>$first->id]);$this->assertCount(1,$report['subscriptions']);$this->assertSame($first->id,$report['subscriptions']->first()->clinic_id);}
 public function test_analytics_component_renders_with_string_url_dates():void{Livewire::test(SubscriptionAnalyticsComponent::class,['from'=>'2026-01-01','to'=>'2026-09-11'])->assertOk()->assertSee('Subscription Analytics')->assertSee('Export CSV');}
 public function test_aging_matches_outstanding_and_page_offers_presets_and_trend():void{$clinic=Clinic::create(['name'=>'Aging Clinic','slug'=>'aging-clinic']);$plan=SubscriptionPlan::create(['name'=>'Basic','code'=>'aging-basic','base_price'=>500,'billing_interval'=>'monthly']);$sub=ClinicSubscription::create(['clinic_id'=>$clinic->id,'subscription_plan_id'=>$plan->id,'status'=>'active','billing_interval'=>'monthly','current_period_starts_at'=>now(),'current_period_ends_at'=>now()->addDays(20)]);foreach([['INV-LATE',now()->subDays(40)],['INV-DUE',now()->addDays(5)]] as [$no,$due])PlatformInvoice::create(['number'=>$no,'clinic_id'=>$clinic->id,'clinic_subscription_id'=>$sub->id,'period_start'=>now(),'period_end'=>now()->addMonth(),'due_date'=>$due,'subtotal'=>250,'tax'=>0,'total'=>250,'amount_paid'=>0,'currency'=>'GHS','status'=>'unpaid']);$report=app(SubscriptionAnalyticsService::class)->report(now()->startOfMonth(),now()->endOfMonth(),['clinic_id'=>$clinic->id]);$this->assertSame(500.0,(float)$report['metrics']['outstanding']);$this->assertSame(250.0,(float)$report['aging']['31-60']);$this->assertSame(250.0,(float)$report['aging']['current']);$this->assertEquals($report['metrics']['outstanding'],$report['aging']->sum());$this->assertSame(500.0,$report['trend']->last()['invoiced']);$this->assertSame(1,$report['metrics']['active_clinics']);$this->assertCount(1,$report['renewals']);
  Livewire::test(SubscriptionAnalyticsComponent::class)->assertSee('Platform navigation')->assertSee('Invoiced vs collected by month')->assertSee('Aging Clinic')->call('preset','month')->assertSet('from',now()->startOfMonth()->toDateString())->set('from',now()->addDay()->toDateString())->set('to',now()->startOfMonth()->toDateString())->assertOk();}
}
